<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="INBOOK_X1_SLIM" ignored="0" name="RetryAnalyzer" tests="6" failures="2" timestamp="28 May 2023 11:35:35 GMT" time="13.49" errors="0">
  <testcase name="tc001" time="4.909" classname="TestNG.Rerun">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at TestNG.Rerun.tc001(Rerun.java:41)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- tc001 -->
  <testcase name="tc002" time="1.659" classname="TestNG.Rerun">
    <skipped/>
  </testcase> <!-- tc002 -->
  <testcase name="tc002" time="0.891" classname="TestNG.Rerun">
    <skipped/>
  </testcase> <!-- tc002 -->
  <testcase name="tc002" time="0.842" classname="TestNG.Rerun">
    <skipped/>
  </testcase> <!-- tc002 -->
  <testcase name="tc002" time="0.797" classname="TestNG.Rerun">
    <skipped/>
  </testcase> <!-- tc002 -->
  <testcase name="tc002" time="0.767" classname="TestNG.Rerun">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at TestNG.Rerun.tc002(Rerun.java:48)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- tc002 -->
</testsuite> <!-- RetryAnalyzer -->
